version: 2
jobs:
  build-4.04:
    docker:
      - image: tmcgilchrist/ci-ocaml:ubuntu_xenial-4.04-20181001033113-0453d11
    steps:
      - checkout
      - run:
          name: Build
          command: ./bin/ci.branches
          environment:
            OCAML_VER: 4.04
            DUNE_VER: 1.5.0

  deploy:
    docker:
      - image: tmcgilchrist/ci-ocaml:ubuntu_xenial-4.04-20181001033113-0453d11
    steps:
      - checkout
      - run:
          name: Build
          command: ./bin/ci
          environment:
            OCAML_VER: 4.04
            DUNE_VER: 1.5.0
workflows:
  version: 2
  build:
    jobs:
      - build-4.04
      - deploy:
          filters:
            branches:
              only: master
