version: 2
jobs:
  build-4.04:
    docker:
      - image: ubuntu:16.04

    steps:
      - checkout
      - run:
          name: Build
          command: ./bin/ci.branches

  deploy:
    docker:
      - image: ubunut:16.04
    steps:
      - checkout
      - run:
          name: Build
          command: ./bin/ci

workflows:
  version: 2
  build:
    jobs:
      - build-4.04
      - deploy:
          filters:
            branches:
              only: master
